# config/application.yml

AWS_ACCESS_KEY: "AKIAJHEJ34TIOGZPIXLQ"
AWS_SECRET_KEY: "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"
AWS_BUCKET:     "flixterbobpolache"
AWS_REGION:     "us-east-1"

SECRET_KEY: sk_test_WOjJs3leCi7Bg2OmFfSomqxx
PUBLISHABLE_KEY: pk_test_Kce6jB6eTgXVWs6G1EMqjKAb
